#include "../include/barberShop.h"

int main()
{
    BarberShop shop;
    int numberOfBarbers = 1, numberOfCustomers = 7;
    std::vector<std::string> names{
        "John",
        "Gregor",
        "Pete",
        "Peter",
        "Oliver",
        "James",
        "Cody",
        "Jeeves",
        "Connor",
        "Hugo",
        "Sam",
        "Herman", "Liam",
        "Noah",
        "Oliver",
        "Elijah",
        "James",
        "William",
        "Benjamin",
        "Lucas",
        "Henry",
        "Theodore",
        "Jack",
        "Levi",
        "Alexander",
        "Jackson",
        "Mateo",
        "Daniel",
        "Michael",
        "Mason",
        "Sebastian",
        "Ethan",
        "Logan",
        "Owen",
        "Samuel",
        "Jacob",
        "Asher",
        "Aiden",
        "John",
        "Joseph",
        "Wyatt",
        "David",
        "Leo",
        "Luke",
        "Julian",
        "Hudson",
        "Grayson",
        "Matthew",
        "Ezra",
        "Gabriel",
        "Carter",
        "Isaac"};
    shop.run(numberOfBarbers, numberOfCustomers, names);
    return 0;
}